// Generated by CoffeeScript 1.7.1
(function() {
  $(document).ready(function() {
    var $input, $submit, isUpperCase;
    $input = $('#input');
    $submit = $('#submit');
    $submit.click(function() {
      var youSay;
      youSay = $input.val();
      console.log(youSay);
      return isUpperCase(youSay)();
    });
    return isUpperCase = function(youSay) {
      youSay === youSay.toUpperCase();
      return console.log(youSay);
    };
  });

}).call(this);
